baseURL = 'https://daniel.tlach.cz/'
languageCode = 'en-us'
title = 'Daniel Tlach'
theme = 'identity'

[params]
paginate = 10
twitter = "danaketh"
github = "danaketh"
npm = "danaketh"
linkedin = "danieltlach"

[[menu.main]]
name = "About"
url = "/"
weight = 1
pageRef = "about"

#[[menu.main]]
#name = "Blog"
#url = "/blog/"
#weight = 2
#pageRef = "blog"

[[menu.main]]
name = "Contact"
url = "mailto:daniel@tlach.cz"
weight = 3

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 80

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = false

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "author"
toLower = true
weight = 30
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
weight = 10
pattern = "2017"



[markup]
[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
noHl = true
style = 'onedark'
tabWidth = 4
