backend:
  name: "github"
  repo: "danaketh/daniel.tlach.cz"
  branch: main
  automatic_deployments: false

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
site_url: "https://daniel.tlach.cz"
locale: "en"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  ## Pages
  - label: "Pages"
    name: "pages"
    files:
      - label: "Curriculum Vitae"
        name: "homepage"
        file: "content/index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
          - label: 'Parameters'
            name: 'params'
            widget: 'object'
            fields:
              - label: 'Navigation ID'
                name: 'nav'
                widget: 'string'
  ## Blog posts
  - name: 'blog'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    folder: 'content/blog'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    editor:
      preview: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
