name: Build and Release Resume

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the release (e.g., v1.0.0 or 2024.07.19)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Specify your Go version

      - name: Run Go preparation script
        run: go run ./bin/prepare_resume.go

      - name: Setup LaTeX and Compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: resume

      - name: Create Release and Upload Resume PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Resume Release ${{ github.event.inputs.version }}
          files: resume/resume.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}